[package]
name = "npuzzle_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
indexmap = "1.9.2"
rand = "0.8.5"
structopt = "0.3.26"
thiserror = "1.0.38"
